-- =============================================================================
-- PAYMENTS TABLE (Flutterwave integration)
-- =============================================================================
-- WHAT THIS FILE DOES
-- --------------------
-- 1. Creates the `payments` table that stores every payment attempt.
-- 2. Adds RLS policies so users can read only their own payments, while the
--    service role (webhook, verify route) can read/write everything.
--
-- HOW TO RUN
-- ----------
-- Run this in the Supabase SQL Editor (Dashboard → SQL → New query).
-- Safe to re-run (idempotent).
--
-- PREREQUISITES
-- -------------
-- Run `entitlements-setup.sql` first (adds plan/is_exempt to profiles).
-- =============================================================================
-- -----------------------------------------------------------------------------
-- 1. Create the payments table
-- -----------------------------------------------------------------------------
create table if not exists public.payments (
    id uuid primary key default gen_random_uuid(),
    -- The Supabase auth user who initiated the payment.
    user_id uuid not null references auth.users(id) on delete cascade,
    -- Flutterwave transaction reference (generated by our app, unique).
    tx_ref text not null unique,
    -- The Flutterwave transaction ID (populated after verification).
    flw_transaction_id bigint,
    amount integer not null,
    currency text not null default 'NGN',
    -- Which product was purchased.
    payment_type text not null check (
        payment_type in ('premium_upgrade', 'team_subscription')
    ),
    -- Lifecycle of the payment.
    status text not null default 'pending' check (
        status in (
            'pending',
            'successful',
            'failed',
            'cancelled',
            'refunded'
        )
    ),
    -- Denormalised customer info (snapshot at payment time).
    customer_email text,
    customer_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
-- Index for looking up a payment by its tx_ref (used by webhook/verify).
create index if not exists idx_payments_tx_ref on public.payments(tx_ref);
-- Index for listing a user's payment history.
create index if not exists idx_payments_user_id on public.payments(user_id);
-- -----------------------------------------------------------------------------
-- 2. Row Level Security
-- -----------------------------------------------------------------------------
alter table public.payments enable row level security;
-- Users can read their own payment records (e.g. to see payment history).
drop policy if exists "Users can read own payments" on public.payments;
create policy "Users can read own payments" on public.payments for
select to authenticated using (auth.uid() = user_id);
-- Users can create their OWN pending payment rows (to start a checkout).
-- This is safe because status defaults to 'pending' and only the service
-- role (verify/webhook routes) can change status to 'successful'.
drop policy if exists "Users can insert own payments" on public.payments;
create policy "Users can insert own payments" on public.payments for
insert to authenticated with check (auth.uid() = user_id);
-- NOTE: No UPDATE/DELETE policies for authenticated users.
-- All status changes happen from the server (service role), which bypasses
-- RLS. The service role is used by:
--   - verify route (UPDATE status after verification)
--   - webhook route (UPDATE status, grant pro)
-- -----------------------------------------------------------------------------
-- 3. Updated_at trigger (auto-maintain the updated_at column)
-- -----------------------------------------------------------------------------
create or replace function public.handle_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now();
return new;
end;
$$;
drop trigger if exists payments_updated_at on public.payments;
create trigger payments_updated_at before
update on public.payments for each row execute function public.handle_updated_at();