import './globals.css';

import {
  Birthstone,
  Inter,
  Metamorphous,
  Outfit,
  Passero_One,
  Playfair_Display,
} from 'next/font/google';
import type { Metadata, Viewport } from 'next';

import ConsentedVercelAnalytics from '@/components/ConsentedVercelAnalytics';
import AppNavbar from '@/components/AppNavbar';
import ConsentedGoogleAnalytics from '@/components/ConsentedGoogleAnalytics';
import CookieConsentBanner from '@/components/CookieConsentBanner';
import PostHogProvider from '@/components/PostHogProvider';
import Script from 'next/script';
import SwRegister from '@/components/SwRegister';
import { Toaster } from 'sonner';
import OnboardingWidget from '@/components/onboarding/OnboardingWidget';

const outfit = Outfit({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-outfit',
});

// Card customization fonts. Exposed as CSS variables so the card layouts can
// apply them via inline styles / Tailwind. These load on every page (small
// subset cost) so a user's chosen font renders even on first paint.
const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-inter',
});
const playfair = Playfair_Display({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-playfair',
});
const passero = Passero_One({
  display: 'swap',
  weight: '400',
  subsets: ['latin'],
  variable: '--font-passero',
});
const metamorphous = Metamorphous({
  display: 'swap',
  weight: '400',
  subsets: ['latin'],
  variable: '--font-metamorphous',
});
const birthstone = Birthstone({
  display: 'swap',
  weight: '400',
  subsets: ['latin'],
  variable: '--font-birthstone',
});

export const metadata: Metadata = {
  // metadataBase resolves relative OG/Twitter image URLs (e.g. "/banner.png")
  // to absolute URLs, which crawlers require.
  metadataBase: new URL('https://www.konneqta.com'),
  title: 'Konneqta',
  description: 'Connect Smarter, Beyond The Internet',
  // NOTE: no root-level canonical here. A layout-level canonical is inherited
  // by every page that doesn't override it — which previously made unrelated
  // pages (e.g. /waitlist, /konneqts) declare the homepage as their canonical.
  // That mismatch is what triggered Google's "Duplicate, Google chose
  // different canonical than user" Search Console warning. Each indexable
  // page now sets its own self-canonical; private pages set noindex instead.
  // The Web App Manifest is generated by app/manifest.ts (Next.js 16 file
  // convention). Next.js auto-injects <link rel="manifest"> here.
  manifest: '/manifest.webmanifest',
  // iOS "Add to Home Screen" — standalone launch, custom status bar.
  appleWebApp: {
    capable: true,
    title: 'Konneqta',
    statusBarStyle: 'black-translucent',
  },
  // Default rich-preview card for non-profile routes (home, login, etc.).
  // Profile pages override these via generateMetadata in app/[username]/page.tsx.
  openGraph: {
    title: 'Konneqta',
    description: 'Connect Smarter, Beyond The Internet',
    siteName: 'Konneqta',
    type: 'website',
    images: [
      {
        url: '/banner.png',
        width: 1200,
        height: 630,
        alt: 'Konneqta',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Konneqta',
    description: 'Connect Smarter, Beyond The Internet',
    images: ['/banner.png'],
  },
  icons: {
    icon: [
      { url: '/favicon-48x48.png', sizes: '48x48', type: 'image/png' },
      {
        url: '/favicon.svg',
        type: 'image/svg+xml',
      },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      // PWA installable icons (regular, non-maskable).
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [
      // High-res icon for iOS home screen + splash. Opaque black bg matches
      // the manifest theme so the launch screen looks intentional.
      {
        url: '/icons/apple-touch-180.png',
        sizes: '180x180',
        type: 'image/png',
      },
    ],
  },
};

// themeColor moved to Viewport in Next.js 14+ (Metadata no longer accepts it).
// This drives the Android PWA status-bar / address-bar tint.
export const viewport: Viewport = {
  themeColor: '#000000',
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={` ${outfit.variable} ${inter.variable} ${playfair.variable} ${passero.variable} ${metamorphous.variable} ${birthstone.variable} h-full antialiased`}
    >
      <head>
        <Script
          id="analytics-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark');
                  } else if (theme === 'light') {
                    // Explicit light choice — set .light so the
                    // prefers-color-scheme fallback in globals.css
                    // (:root:not(.light)) can't re-apply dark variables.
                    document.documentElement.classList.add('light');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      {/* bg-black prevents a white flash on PWA launch / splash before CSS
          hydrates; matches the manifest background_color (#000000). */}
      <body
        className="min-h-full flex flex-col bg-black"
        suppressHydrationWarning
      >
        <PostHogProvider>
          {children}
          <Toaster position="top-right" richColors />
          <OnboardingWidget />
          <ConsentedVercelAnalytics />
          {/* Registers /sw.js in production only (Serwist offline shell). */}
          <SwRegister />
          {/* Auth-gated navbar (hamburger + side drawer) — logged-in users only. */}
          <AppNavbar />
        </PostHogProvider>
        <CookieConsentBanner />
        {/*
          Google Analytics — the ONLY loader lives in ConsentedGoogleAnalytics:
          consent-gated ("Accept all") AND lazyOnload (the ~159 KiB gtag.js
          bundle fetches after first paint + interactivity). Do NOT add a
          second gtag injection here — it would double-count every pageview
          and track users who chose "Necessary only".
        */}
        <ConsentedGoogleAnalytics />
      </body>
    </html>
  );
}
